// <auto-generated />
using System;
using Condominiosdotcom.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Condominiosdotcom.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Condominiosdotcom.Api.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Condominiosdotcom.Api.Models.Condominio", b =>
                {
                    b.Property<int>("CondominioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apart_casa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<string>("NombreCondominio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidencialID")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("CondominioID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("ResidencialID");

                    b.ToTable("Condominio");
                });

            modelBuilder.Entity("Condominiosdotcom.Api.Models.Cuotas", b =>
                {
                    b.Property<int>("CuotaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<int>("PagoID")
                        .HasColumnType("int");

                    b.HasKey("CuotaID");

                    b.HasIndex("PagoID");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("Condominiosdotcom.Api.Models.Pagos", b =>
                {
                    b.Property<int>("PagoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int?>("CondominioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<int>("Mora")
                        .HasColumnType("int");

                    b.Property<int>("Pendiente")
                        .HasColumnType("int");

                    b.HasKey("PagoID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("CondominioID");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Condominiosdotcom.Api.Models.Residencial", b =>
                {
                    b.Property<int>("ResidencialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreResidencial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidencialID");

                    b.ToTable("Residencial");
                });

            modelBuilder.Entity("Condominiosdotcom.Api.Models.Condominio", b =>
                {
                    b.HasOne("Condominiosdotcom.Api.Models.Cliente", "ClienteE")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condominiosdotcom.Api.Models.Residencial", "ResidencialE")
                        .WithMany()
                        .HasForeignKey("ResidencialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteE");

                    b.Navigation("ResidencialE");
                });

            modelBuilder.Entity("Condominiosdotcom.Api.Models.Cuotas", b =>
                {
                    b.HasOne("Condominiosdotcom.Api.Models.Pagos", "PagosE")
                        .WithMany()
                        .HasForeignKey("PagoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PagosE");
                });

            modelBuilder.Entity("Condominiosdotcom.Api.Models.Pagos", b =>
                {
                    b.HasOne("Condominiosdotcom.Api.Models.Cliente", "ClienteE")
                        .WithMany()
                        .HasForeignKey("ClienteID");

                    b.HasOne("Condominiosdotcom.Api.Models.Condominio", "CondominioE")
                        .WithMany()
                        .HasForeignKey("CondominioID");

                    b.Navigation("ClienteE");

                    b.Navigation("CondominioE");
                });
#pragma warning restore 612, 618
        }
    }
}
